### ISSUE TITLE
Suggestion to extend capabilities of upgrade-script.sh

### ISSUE THREAD

**Issue by ember1205** [sdetweil/MagicMirror_scripts#19]
Since this script already contains the basics of a number of things, I would like to suggest enhancing its abilities for the purposes of being used in a more automated fashion.

- Add support for various command line options, starting with one to check version. Output should show currently installed local version of MM.
- New command line option to check for upgrade. Output should show currently installed local version of MM and available version or "current" (or similar) if no upgrade available.
- Add support for IFTTT/PushOver or other notification systems (I can help here as I have a structure already being used elsewhere for both).
- Add support for command line option to indicate running in automated / batch mode. Default from this would be to write output to log files and support sending of notifications that it had run (and to check the logs).

**Comment by sdetweil** [comment]
go for it. don't break existing function

tricky spots, if there are changed files, what does that mean? 

watch out for prompts

**Comment by ember1205** [comment]
I've been going through your script and am wondering if you have a general echoed output that says an upgrade is available? What about general output that indicates whether an upgrade should proceed ok or if there are issues?

What I'm thinking is that it might be easiest to write a separate script to check for updates and then call your script (if one is found) to test for whether the upgrade can proceed or if there are issues. Capturing that output and then sending a notification via the secondary script would be very easy at that point.

**Comment by sdetweil** [comment]
no, I assume users will only run this when a new release IS available.. I DO check to see if github version is newer than installed. 

u can use that code line 172
```
		  # get the local and remote package.json versions
			local_version=$(grep -m1 version package.json | awk -F\" '{print $4}' | awk -F-  '{print $1}')
			remote_version=$(curl -s https://raw.githubusercontent.com/MichMich/MagicMirror/master/package.json | grep -m1 version | awk -F\" '{print $4}')
```
as part of a  recurring test.. remember MM is on a 90 day release cycle, Jan 1, April 1, July 1, Oct 1

I don't have any pre-parms to override the prompts..

**Comment by ember1205** [comment]
I also noticed that the upgrade script opts to overwrite existing files with newer ones, including files like package.json that may have been locally modified (like where I changed out the "start" command to launch a script that runs chromium instead of electron). Have you considered moving certain modifications into a secondary file and then stream editing them into the new files so that modifications can persist across versions? 

Package.json is somewhat special of a use case since it directly contains the MM version number. So, updating it when upgrades are performed makes sense. But, if that's the case, then maybe modifying it locally should be handled differently like with SED to swap out certain commands?

**Comment by sdetweil** [comment]
i give the user the option of saving the files (git stash)  lock files don't need to be saved.
git merge exposes those changes..  if the script was used (pi 0, mine) then I put it back.. after the update
you shouldn't need to know I hacked it, unless you have some different script , then u are on your own (altho I gave u heads up in both test and apply runs there were changes that needed to be accounted for

I use sed to change package.json

**Comment by ember1205** [comment]
Give the user the option to save... Agreed. Don't need to save lock files... Agreed.

When running the update with "apply", however, a lock file DID get saved in the stash as it was identified...

(from the test run):

`saving custom.css
upgrading from version 2.12.0 to 2.13.0
fetching latest revisions
there are 3 local files that are different than the master repo

   modules/default/weatherforecast/weatherforecast.js
   package.json
   vendor/package-lock.json

any *-lock.json files do not need to be saved
do you want to save these files for later   (Y/n)?
processing dependency changes for active modules with package.json files

processing for module MMM-ImagesPhotos please wait
----------------------------------
skipped processing for MMM-ImagesPhotos, doing test run
processing complete for module MMM-ImagesPhotos

restoring custom.css
test run, restoring files stashed
`

When running the script with only the 'apply' option, the newer files replace the older ones, the older ones are stashed, and the user is told to restore them if they want. The new package.json contains the original "start" section and the edited portion to launch "./runstart.sh" instead is gone. This is why I was thinking along the lines of having a secondary file with custom content that would be used to replace specific lines in the new package.json as leaving the old one in place would cause an issue with versioning (it would still show the old version).

From the output above, you can see nothing was mentioned about merging, but there is mention of it when running with the 'apply' parameter. And, even though it was apparently run, the "./runstart.sh" script was missing from my configuration. Thoughts on this? 

I'm trying to be certain that I understand your script adequately before I try and write a wrapper to go around it or interact with it.

**Comment by sdetweil** [comment]
can u send the the installers/upgrade.log, the code says it should change the package.json to include the run-start.sh script..
(only during apply phase of course)

**Comment by sdetweil** [comment]
thanks i fixed the package-lock to the stash, and re-validated that the run-start is there and added to the package.json 

upgraded from 2.11 to 2.13 on my pi 0 which depends on the run-start... 
I checked this by cpu architecture, NOT by presence of run-start.sh

**Comment by ember1205** [comment]
How would you like me to provide the logs?

My upgrade was 2.12 to 2.13 if that matters, and I used the script you had updated in the last week or so. Pi3 Model B v1.2

**Comment by sdetweil** [comment]
attach here 
ok, I wouldn't have put the run-start.sh back.. maybe I need to test it its being used.. pi3 is armv7l

**Comment by ember1205** [comment]
A grep of the package.json file for "runstart.sh" could identify it and flag it for updating... ?
[upgradelog.txt](https://github.com/sdetweil/MagicMirror_scripts/files/5341692/upgradelog.txt)

**Comment by sdetweil** [comment]
done, will fix if found used before upgrade

**Comment by ember1205** [comment]
Great. I'll try it on the other mirror to see how it ends up. 

Does the script accept any command line parameters currently besides "apply"? It doesn't appear to , but wanted to be sure.

**Comment by sdetweil** [comment]
it accepts force, if the versions are the same, you can force it on again (in case some manual upgrade failed or whatever, had this because the script failed after merge at one time)

**Comment by sdetweil** [comment]
i saved a copy of my 2.11 so I can copy it in again and then try upgrade again

**Comment by ember1205** [comment]
Doing a test run of 2.12 to 2.13 and I'm still seeing it show "vendor/package-lock.json" as a file to be saved. Should it show that still?

**Comment by sdetweil** [comment]
gotta fix that too, thanks

**Comment by sdetweil** [comment]
uploaded fix to erase them (vendor and fonts) , still says they are changed..

**Comment by ember1205** [comment]
Should it still show them as "to be stashed"?

**Comment by sdetweil** [comment]
i am currently not editing the list of files returned as changed

**Comment by ember1205** [comment]
Gotcha.

Just thought about this as an idea: What about adding s version number to your script and outputting that when it's run?

**Comment by sdetweil** [comment]
thought about it 100 times, but unlikely to be an issue.. either they ran it today or yesterday... not 100 days ago.. 
force can redo it if some needs to be fixed on a broads scale, that can't be fixed by a file edit. or manual command execution

**Comment by sdetweil** [comment]
I'm going to close this now.. I don't think there is value in running just for the sake of getting feedback on versions..
